option(${MODULE_NAME}_BUILD_EXAMPLES "Build examples for core part of project" ${${MAIN_PROJECT_NAME}_DEVELOPER_MODE})
option(${MODULE_NAME}_BUILD_TESTS "Build tests for core part of project" ${${MAIN_PROJECT_NAME}_DEVELOPER_MODE})

option(${MODULE_NAME}_ENABLE_COVERAGE "Enable coverage flags" ${${MAIN_PROJECT_NAME}_ENABLE_COVERAGE})

option(${MODULE_NAME}_ENABLE_CLANGTIDY_ON_BUILD " " "${${MAIN_PROJECT_NAME}_ENABLE_CLANGTIDY_ON_BUILD}")
option(${MODULE_NAME}_ENABLE_CPPCHECK_ON_BUILD " " "${${MAIN_PROJECT_NAME}_ENABLE_CPPCHECK_ON_BUILD}")
option(${MODULE_NAME}_ENABLE_IWYU_ON_BUILD " " "${${MAIN_PROJECT_NAME}_ENABLE_IWYU_ON_BUILD}")

option(${MODULE_NAME}_SANITIZER_ADDRESS "Enable SANITIZER_ADDRESS for the `core` project" ${${MAIN_PROJECT_NAME}_DEVELOPER_MODE})
option(${MODULE_NAME}_SANITIZER_LEAK "Enable SANITIZER_LEAK for the `core` project" OFF)
option(${MODULE_NAME}_SANITIZER_UNDEFINED_BEHAVIOR "Enable SANITIZER_UNDEFINED_BEHAVIOR for the `core` project" ${${MAIN_PROJECT_NAME}_DEVELOPER_MODE})
option(${MODULE_NAME}_SANITIZER_THREAD "Enable SANITIZER_THREAD for the `core` project" OFF)
option(${MODULE_NAME}_SANITIZER_MEMORY "Enable cSANITIZER_MEMORY for the `core` project" OFF)