option(my_project_ENABLE_IPO "enable interprocedural optimization can be enabled")
macro(my_project_enable_ipo)
    if(my_project_ENABLE_IPO)
        include(CheckIPOSupported)
        check_ipo_supported(RESULT result OUTPUT output)
        if(result)
            set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
        else()
            message(WARNING "IPO is not supported: ${output}")
        endif()
    endif()
endmacro()
