name: CMake on unix platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        c_compiler: [gcc, clang]
        ci_preset_suffix: [ubuntu]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    - run: uv sync --frozen --no-install-project

    - name: Configure CMake
      run: |
        source .venv/bin/activate
        cmake --preset ci-${{ matrix.ci_preset_suffix }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Build
      run: cmake --build --preset ci-${{ matrix.ci_preset_suffix }}-release

    - name: Test
      run: ctest --preset ci-${{ matrix.ci_preset_suffix }}-test-release

    - name: Package
      run: cpack --preset ci-${{ matrix.ci_preset_suffix }}-package
      
