name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            ci_os: ubuntu
            activate_cmd: source .venv/bin/activate
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            ci_os: ubuntu
            activate_cmd: source .venv/bin/activate

    steps:
    - uses: actions/checkout@v4
    
    - name: Install pipx and uv
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install uv
      shell: bash

    - name: Install Conan via uv
      run: |
        uv venv 
        uv sync
      shell: bash

    - name: Configure CMake
      run: |
        ${{ matrix.activate_cmd }}
        cmake --preset ci-${{ matrix.ci_os }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Build
      run: |
        ${{ matrix.activate_cmd }}
        cmake --build --preset ci-${{ matrix.ci_build_presets }}-release

    - name: Test
      run: |
        ${{ matrix.activate_cmd }}
        ctest --preset ci-${{ matrix.ci_test_presets }}-test-release

    - name: Package
      run: |
        ${{ matrix.activate_cmd }}
        cpack --preset ci-${{ matrix.ci_pack_presets }}-package
      
